import Head from 'next/head'
import { LandingPage } from '../src/components'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nocturn Store</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <LandingPage />
      </main>
    </div>
  )
}
